### ISSUE TITLE
A little sb problem in your script.

### ISSUE THREAD

**Issue by iflody** [Kira-cxy/pwn-script#1]
Hi!

These days, I had used your script to help me debug the program which has the PIE protection, but I think there is a very silly design in your code logic.

Why I need to use RA before I set break point in the program, I think this is really silly, I think your code is just a shit!

Please fix the problem as quick as possible!

**Comment by Kira-cxy** [comment]
Confirmed.

**Comment by Kira-cxy** [comment]
Fixed. Please check the newest version.
